### ISSUE TITLE
[BUG] mx.fft.irfftn is inconsistent with np

### ISSUE THREAD

**Issue by stockeh** [ml-explore/mlx#1592] opened 2024-11-16 21:44 UTC
**Describe the bug**
`mx.fft.irfftn(a, s)` is giving different results than `np.fft.irfftn(a, s)` with the same parameters for `a` and `s`.  The examples below use `a.shape=(4, 256, 256)` with `a.dtype=mlx.core.complex64`.

See the `sample` function below along with the code to reproduce. Does this have to do with dimensionality? 

```python
# mlx (0.20.0)
def sample(self, N: int) -> np.ndarray:
    a = (
        mx.random.normal((N, *self.size)) + 1j * mx.random.normal((N, *self.size))
    ) * self.sqrt_eig
    return mx.fft.irfftn(a, self.size) # ONLY DIFFERENCE
```
![random_field_mlx](https://github.com/user-attachments/assets/0ea84361-0fbe-45e1-946f-b2492a636a83)

```python
# numpy (1.26.4)
def sample(self, N: int) -> np.ndarray:
    a = (
        mx.random.normal((N, *self.size)) + 1j * mx.random.normal((N, *self.size))
    ) * self.sqrt_eig
    return np.fft.irfftn(a, self.size) # ONLY DIFFERENCE
```
![random_field_np](https://github.com/user-attachments/assets/df6056cf-73eb-458e-8d8c-5f68242be21d)

**To Reproduce**

```python
from typing import Union

import matplotlib.pyplot as plt
import mlx.core as mx
import numpy as np


class GaussianRF:
    """Generates Gaussian Random Fields."""

    def __init__(
        self,
        dim: int,
        size: int,
        length: float = 1.0,
        alpha: float = 2.0,
        tau: float = 3.0,
        sigma: Union[float, None] = None,
        constant_eig: bool = False,
    ) -> None:
        self.dim = dim
        self.size = size
        self.length = length
        self.alpha = alpha
        self.tau = tau
        self.sigma = sigma or tau ** (0.5 * (2 * alpha - dim))
        self.constant_eig = constant_eig

        self.k_max = size // 2
        self.const = (4 * (mx.pi**2)) / (length**2)

        self.k = mx.concat(
            (
                mx.arange(0, self.k_max),
                mx.arange(-self.k_max, 0),
            ),
            axis=0,
        )

        self.sqrt_eig = self._compute_sqrt_eig()
        self.size = (size,) * dim

    def _compute_sqrt_eig(self) -> mx.array:
        mesh = mx.meshgrid(*(self.k,) * self.dim, indexing="ij")
        k_sq = sum(k_i**2 for k_i in mesh)
        sqrt_eig = (
            (self.size**self.dim)
            * mx.sqrt(2)
            * self.sigma
            * ((self.const * k_sq + self.tau**2) ** (-self.alpha / 2.0))
        )
        if self.constant_eig:
            sqrt_eig[(0,) * self.dim] = (
                (self.size**self.dim) * self.sigma * (self.tau ** (-self.alpha))
            )
        return sqrt_eig

    def sample(self, N: int) -> np.ndarray:
        a = (
            mx.random.normal((N, *self.size)) + 1j * mx.random.normal((N, *self.size))
        ) * self.sqrt_eig
        # return np.fft.irfftn(a, self.size)
        return mx.fft.irfftn(a, self.size)


if __name__ == "__main__":
    resolution = 256
    n_samples = 4

    grf = GaussianRF(
        dim=2, size=resolution, alpha=3 / 2, tau=mx.sqrt(196), sigma=mx.sqrt(14)
    )
    w0 = grf.sample(n_samples)

    #! plotting
    fig, axs = plt.subplots(1, n_samples, figsize=(2 * n_samples, 2))
    axs = axs.tolist() if n_samples > 1 else [axs]
    for i, ax in enumerate(axs):
        ax.imshow(w0[i], cmap="twilight")
        ax.axis("off")
    plt.tight_layout()
    plt.show()
    # fig.savefig("random_field_mlx.png", dpi=300, bbox_inches="tight")

```

**Expected behavior**
The NumPy output is correct and MLX should match, according to the tests (see [python/tests/test_fft.py](https://github.com/ml-explore/mlx/blob/610af352d4788dc63549a0d54a708ff028db414c/python/tests/test_fft.py#L70)). 

**Desktop (please complete the following information):**
 - OS Version: MacOS 15.1
 - numpy: v1.26.4 
 - mlx: v0.20.0

**Comment by awni** [comment] 2024-11-17 14:18
I'm not able to reproduce this and I suspect it could be related to a recent [bug we fixed](https://github.com/ml-explore/mlx/pull/1566) (which impacted FFT and a couple other kernels).

Two comments on your test:
1. I don't see a seed, so if you run it twice you won't get the same results
2. Following NumPy 2.0, in the next version of MLX we deprecated not specifying axes when sizes are given to fftn / ifftn / etc. So you will need to specify `axes=(1, 2)` to the `irfftn` call.

I'm going to close this as resolved since this seems to be fixed in the latest MLX. We should release that to PyPi next week. If you still have issues please comment here and we can reopen.

**Closed by awni** 2024-11-17 14:18 UTC

**Comment by stockeh** [comment] 2024-11-22 21:40
No issues with v0.21.0 🙂
