### ISSUE TITLE
[BUG maybe?] mx.linalg.svd() should fallback to cpu instead of crashing if default device is set to gpu

### ISSUE THREAD

**Issue by adhulipa** [ml-explore/mlx#847] opened 2024-03-19 02:20 UTC
**Describe the bug**
SVD (and likely other linalg ops such as qrf, inv) should not crash if Metal version is unimplemented

**To Reproduce**

Include code snippet
```python

>>> A = mx.array([[1, 2, 1],
...        [3, 4, 2],
...        [2, 2, 1]], dtype=mx.float32)

>>> mx.set_default_device(mx.gpu)
>>> mx.linalg.svd(A)
libc++abi: terminating due to uncaught exception of type std::runtime_error: [SVD::eval_gpu] Metal SVD NYI.
fish: Job 1, 'ptpython' terminated by signal SIGABRT (Abort)

```

**Expected behavior**
Fallback to CPU impl and run svd using accelerate/lapack

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.1.2] 23E214
 - Version [e.g. 0.7.0] mlx mainline editable install

**Additional context**
Curious about SVD PR design choice here: https://github.com/ml-explore/mlx/pull/809/files#diff-47ed9ccadffa0bbecd087f4f617acf4276f17bbefdb8ecf404f64fee93f64963R893-R896
  
For example, when compared to `Transpose()` function a few lines above:
1. is it correct to say that on lines 883-885 `Transpose::eval_gpu()` is falling back to `mlx/backend/common/primitives.cpp:797` where we run `void Transpose::eval(const std::vector<array>& inputs, array& out)`?
2. Item 1. doesn't seem to be a Metal kernel or operation, right?
3. So, im curious why we chose to throw a runtime error here? Perhaps it might make sense to call `SVD::eval()` while printing a warning saying "Metal SVD NYI"

Otherwise, inadvertently we could be crashing the python program if the user doesn't set `mx.set_default_device(mx.cpu)`

```
>>> mx.set_default_device(mx.cpu)
>>> A = mx.array([[1, 2, 1],
...        [3, 4, 2],
...        [2, 2, 1]], dtype=mx.float32)
>>>
>>> mx.linalg.svd(A)
(array([[-0.365019, -0.730361, -0.57735],
       [-0.815021, -0.0490655, 0.57735],
       [-0.450002, 0.681296, -0.57735]], dtype=float32), array([6.6073, 0.586167, 6.03565e-09], dtype=float32), array([[-0.561513, -0.74011, -0.370055],
       [0.827468, -0.502233, -0.251116],
       [4.33917e-08, -0.447214, 0.894427]], dtype=float32))

>>> mx.set_default_device(mx.gpu)
>>> mx.linalg.svd(A)
libc++abi: terminating due to uncaught exception of type std::runtime_error: [SVD::eval_gpu] Metal SVD NYI.
fish: Job 1, 'ptpython' terminated by signal SIGABRT (Abort)
```

**Comment by awni** [comment] 2024-03-19 02:30
So this is not a bug but expected / intentional. The idea is that you have to explicitly ask for the cpu implementation `mx.svd(a, stream=mx.cpu)` if you want to use `svd`. We don't fall back to actual CPU computation in the GPU ops because it is a bit misleading if you are expecting an accelerated function and get a CPU implementation.

As for transpose, that is an exception because there is no kernel launch for either the CPU or GPU (it's just a reordering of some strides and shapes but otherwise a no-op). So calling the `eval` from both is just a simple way to share a common implementation.

I'm going to close this as it's not a bug and we don't intend to change, but feel free to add to the discussion if you have additional thoughts.

**Closed by awni** 2024-03-19 02:30 UTC

**Comment by adhulipa** [comment] 2024-03-19 02:50
I see.  I think it makes sense that falling back could be misleading.  But, seeing a runtime error that crashes the IDLE/PtPython process _felt_ a bit jarring.  It means, I would've lost all my state up until that point and now have to restart the kernel.

I wonder if there's a way to throw a non-fatal error. Is that not possible given that we're talking about an error originating in cpp and transferring that over to python?

**Comment by awni** [comment] 2024-03-19 02:55
We could fail in the op for now instead of in the eval (so you get the error sooner). I suppose a non fatal error is also an option.. it could be a warning or something, that is not unreasonable. You can also always wrap your code in a try catch..

**Comment by adhulipa** [comment] 2024-03-19 04:13
I like the idea of a non-fatal error. Perhaps worth a code change to test it out. I'll share more when I get a chance to tinker. (We can keep this issue closed regardless). Thanks for the discussion!

**Comment by zcbenz** [comment] 2024-04-22 00:14
> You can also always wrap your code in a try catch..

@awni It seems that this error can not be caught on language binding's side, it is thrown from the StreamThread instead of the main thread where script runs, so it is always a hard crash.

```
* thread #9, stop reason = signal SIGABRT
    frame #0: 0x000000018ddbe0dc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x18ddbe0dc <+8>:  b.lo   0x18ddbe0fc               ; <+40>
    0x18ddbe0e0 <+12>: pacibsp 
    0x18ddbe0e4 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x18ddbe0e8 <+20>: mov    x29, sp
Target 0: (node) stopped.
(lldb) bt
  * frame #0: 0x000000018ddbe0dc libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000018ddf5cc0 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x000000018dd01a40 libsystem_c.dylib`abort + 180
    frame #3: 0x000000018ddad070 libc++abi.dylib`abort_message + 132
    frame #4: 0x000000018dd9d110 libc++abi.dylib`demangling_terminate_handler() + 320
    frame #5: 0x000000018da4399c libobjc.A.dylib`_objc_terminate() + 160
    frame #6: 0x000000018ddac434 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x000000018ddaf520 libc++abi.dylib`__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 88
    frame #8: 0x000000018ddaf464 libc++abi.dylib`__cxa_throw + 308
    frame #9: 0x0000000126e9e104 node-mlx.node`mlx::core::SVD::eval_gpu(std::__1::vector<mlx::core::array, std::__1::allocator<mlx::core::array>> const&, std::__1::vector<mlx::core::array, std::__1::allocator<mlx::core::array>>&) + 60
    frame #10: 0x0000000126e968f4 node-mlx.node`std::__1::__function::__func<mlx::core::metal::make_task(mlx::core::array, bool)::$_2, std::__1::allocator<mlx::core::metal::make_task(mlx::core::array, bool)::$_2>, void ()>::operator()() + 268
    frame #11: 0x0000000126704b40 node-mlx.node`mlx::core::scheduler::StreamThread::thread_fn() + 524
    frame #12: 0x0000000126704d04 node-mlx.node`void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (mlx::core::scheduler::StreamThread::*)(), mlx::core::scheduler::StreamThread*>>(void*) + 72
    frame #13: 0x000000018ddf6034 libsystem_pthread.dylib`_pthread_start + 136
```

**Comment by awni** [comment] 2024-04-22 14:09
> @awni It seems that this error can not be caught on language binding's side, it is thrown from the StreamThread instead of the main thread where script runs, so it is always a hard crash.

Good point. We could fix it by throwing in the op instead of the primitive.
