### ISSUE TITLE
Quantisation Support

### ISSUE THREAD

**Issue by okpatil4u** [ml-explore/mlx#13] opened 2023-12-06 06:29 UTC
Hello there, great work !

I was checking if models with int8, int5, int4 quant formats can be used with this package ? Could you please create an example if possible ?

**Comment by robertritz** [comment] 2023-12-07 03:43
Yes! If quantized models are supported I will be moving away from llama.cpp and over to MLX. Prompt evaluation is still tediously slow on M series with llama.cpp and it seems that MLX will speed this up greatly.

**Comment by tanliboy** [comment] 2023-12-07 07:48
> it seems that MLX will speed this up greatly.
I am not sure about this and look for more data points. 
I tested llama.cpp and mlx on the 16 bits llama 7b chat model on M1, and they had similar performance.

**Comment by robertritz** [comment] 2023-12-07 08:30
I don't think it will improve overall tokens per second. But time to first token is what the issue is right now. 

For large prompts it can take almost 10 seconds to get a response.

**Comment by okpatil4u** [comment] 2023-12-07 09:04
Are you sure ? For me prompt evaluation was almost instantaneous. I used
Joe Biden’s entire wikipedia intro and it generated the early life section
in no time.

**Comment by robertritz** [comment] 2023-12-07 09:23
To be clear I'm referring to llama.cpp (I'm using the Python bindings). For long prompts, it takes several seconds for me to get a response. Are you referring to llama.cpp?

**Comment by okpatil4u** [comment] 2023-12-07 09:25
Aah, I was saying that mlx is faster. Yes, llama.cpp is very slow for
evaluation.

**Comment by robertritz** [comment] 2023-12-07 09:28
Yep that's why I'm so interested in mlx. Slow evaluation is the main shortcoming of local LLMs on Macs right now.

**Comment by robertritz** [comment] 2023-12-08 01:15
@tanliboy I haven't done any testing that was recorded. But here is my anecdotal experience. When a model is first loaded with llama.cpp (not kept in RAM but lazy loaded) the first message takes at least 1-2 seconds for short prompts. Follow up questions are quicker. 

I'm not sure why this is re the internals of llama.cpp, but it's what I have experienced. The longer the initial prompt the longer the delay. 

I'm mostly using 4 bit quantizations of 7B and 13B models locally on M series Macs. I would also love to have support for BERT models so Sentence Transformer models could work efficiently without needing the entire torch library installed (300+ MB). 

But I also realize this is no easy task.

**Comment by vade** [comment] 2023-12-08 03:59
WRT to Llama.cpp startup - It could be initial CoreML model compilation. GGML (the runtime) can leverage the ANE, and I think (?) the tokenizer can run on CoreML, just like Whisper, and by default its enabled. Other paths run Metal / CPU via GGML tensor ops by default? 

Whisper.cpp can have the same issue depending on how its compile flags are set and what model is being used internally? 

Sorry if thats off topic.

**Comment by MikeyBeez** [comment] 2024-01-07 20:49
You can use quantized models with Ollama, but the quality is poor.  https://www.youtube.com/watch?v=7BH4C6-HP14

**Comment by angeloskath** [comment] 2024-01-09 22:29
Closing as we now support quantized models and it is as easy as `nn.QuantizedLinear.quantize_module(model)`. There are also a lot of quantized models in the http://github.com/ml-explore/mlx-examples/ .

**Closed by angeloskath** 2024-01-09 22:29 UTC
Labels: enhancement
