### ISSUE TITLE
Memory usage feels weird

### ISSUE THREAD

**Issue by adi** [ml-explore/mlx#239] opened 2023-12-21 15:38 UTC
On a M1 Max 32GB I can load mistral or phi2 but when I look at RAM usage I see strange things:

- Mistral 7B occupies ~14GB as it should 👍 
- Phi2 ~20GB. Why? 👎 

Also when trying to save a model to disk (mistral for example) the RAM usage grows suddenly to 30+GB and then runs out of swap too and crashes with an OOM. I've quit all the apps on this machine and looks like 26GB of RAM & 6GB of swap are just for MLX.

Lastly, I tried training a lore on mistral and after 60 iterations, it suddenly OOMed.

**Comment by awni** [comment] 2023-12-21 15:42
Could you share commands and/or code snippets to reproduce this?

**Comment by adi** [comment] 2023-12-21 15:58
MLX version is the one from the main branch at commit b3916cbf2beb9e18535d21d20012756ec671c055
OS version: 14.1 (23B74)

I'm running the thing like this:
```bash
python3 mistral.py --model_path ~/work/models/mistral-7B-v0.1-mlx/
```

In mlx-examples/llms/mistral/mistral.py I added the below quantization:

```python
    print("[INFO] Loading model from disk.")
    model, tokenizer = load_model(args.model_path)

    print("[INFO] Quantizing model.")
    nn.layers.QuantizedLinear.quantize_module(model)

    print("[INFO] Starting generation...")
```

and generation runs fine after that but memory usage goes up a few gigabytes instead of down.

If I also add saving to disk like this:

```python
    print("[INFO] Loading model from disk.")
    model, tokenizer = load_model(args.model_path)

    print("[INFO] Quantizing model.")
    nn.layers.QuantizedLinear.quantize_module(model)

    print("[INFO] Saving model back to disk.")
    model.save_weights(args.model_path+"/weights_quant.npz")

    print("[INFO] Starting generation...")
```

memory usage goes towards infinity.

First I suspected it's my fault (as I'm using bleeding edge quantization from last night's code) but then I loaded phi2 without any modifications to the scripts and it used around ~20GB of RAM.

**Comment by awni** [comment] 2023-12-21 16:01
Thanks for the input! We'll see if we can reproduce this.

**Comment by angeloskath** [comment] 2023-12-21 19:25
@adi I am quite struggling to reproduced this :-/ 

On my M2 air running `asitop` I am idling at ~10GB memory out of 24GB. When running mistral it peaks at ~20GB which is probably because a couple of the 10 are swapped out. With phi2 it peaks at 17.5GB.

Now, I did reproduce the memory blowup when saving the model. Basically, automatic evaluation (like when printing an array) tries to be smart in figuring out whether to retain the graph or not. In this case (savez) we forgot about it and always retain the graph. This means that the quantization graph is retained as if we wanted to compute gradients for it. I will push a fix but in the mean time you can simply call eval after quantization as follows:

```
print("[INFO] Quantizing model.")
nn.layers.QuantizedLinear.quantize_module(model)
mx.eval(model.parameters()) # <-- this actually runs the computation
```

**Comment by awni** [comment] 2023-12-22 05:19
Fixed in #247

**Closed by awni** 2023-12-22 05:19 UTC

**Comment by adi** [comment] 2023-12-22 05:57
You're doing amazing work here, mlx is a blast and I can't wait for the next features.

I can confirm a few things:
- In version 0.0.6 saving the model no longer consumes all the RAM.
- Saving a quantized model works
- Loading a quantized model works with a bit of tweaking the load_model and it's a lot faster than the unquantized one
- Used RAM with an quantized and unquantized model for Mistral is not different which is again weird.
- I still feel that phi2 RAM consumption of ~20GB is above what I expected in float16 to be around ~6GB

I haven't tested if training a lora still crashes after a few tens of iterations but I'll report on it when I do.

My load_model looks like this:
```python
def load_model(folder: str, dtype=mx.float16, quantize=False):
    model_path = Path(folder)
    tokenizer = Tokenizer(str(model_path / "tokenizer.model"))
    with open(model_path / "config.json", "r") as f:
        config = json.loads(f.read())
        config.pop("sliding_window", None)
        config.pop("model_type", None)
        model_args = ModelArgs(**config)
    model_file = "weights.npz"
    if quantize:
        model_file = "weights.quant.npz"
    weights = mx.load(str(model_path / model_file))
    weights = tree_unflatten(list(weights.items()))
    if not quantize:
        weights = tree_map(lambda p: p.astype(dtype), weights)
    model = Mistral(model_args)
    if quantize:
        nn.layers.QuantizedLinear.quantize_module(model)
    model.update(weights)
    return model, tokenizer
```

**Comment by awni** [comment] 2023-12-22 06:08
> Used RAM with an quantized and unquantized model for Mistral is not different which is again weird.

Actually it's very difficult to get a good reading on how much memory the model actually needs to run fast vs how much it's using. Our allocator is pretty greedy and will take up and hole memory memory even if it could get away with using a lot less.

We could have a mode which limits that behavior / or changes it in some way. But I can tell you that a 7B quantized model runs fine in 8GB (and maybe with even less RAM) whereas a 16-bit model needed well over 16GB to run fast.

**Comment by awni** [comment] 2023-12-22 06:10
> Loading a quantized model works with a bit of tweaking the load_model and it's a lot faster than the unquantized one

I would pull the latest example. It should work without you needing to hack around the dtype. In the new examples it just uses the precision of the model you load.

**Comment by awni** [comment] 2023-12-22 06:11
> I haven't tested if training a lora still crashes after a few tens of iterations but I'll report on it when I do.

Keep us posted! Maybe file a separate issue on that if it is an issue that is!
