### ISSUE TITLE
[BUG] Reduction ops don't support int64/uint64 dtype on GPU

### ISSUE THREAD

**Issue by dc-dc-dc** [ml-explore/mlx#452] opened 2024-01-13 19:43 UTC
**Describe the bug**
Reduction ops not supported for int64/uint64 dtype on gpu device, works fine on cpu

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
mx.ones((2,2,2), dtype=mx.int64).mean() # aborts std::runtime_error: [Reduce::eval_gpu] Does not support int64
mx.ones((2,2,2), dtype=mx.int64).prod() # aborts std::runtime_error: [Reduce::eval_gpu] Does not support int64
```

**Expected behavior**
```python
import mlx.core as mx
mx.ones((2,2,2), dtype=mx.int64).mean(stream=mx.cpu)
# array(1, dtype=float32)
```

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.1.2
 - Version: 0.9

**Comment by awni** [comment] 2024-01-14 18:29
Hey - that's not a bug. At the moment, we don't have support for reductions with 64-bit integers in Metal.. simply a matter of low priority. Closing as dup of #293

**Closed by awni** 2024-01-14 18:29 UTC
