### ISSUE TITLE
[BUG] AttributeError: 'Model' object has no attribute '_no_grad'

### ISSUE THREAD

**Issue by Blaizzy** [ml-explore/mlx#1393] opened 2024-09-04 09:13 UTC
**Describe the bug**

When I try to freeze the model parameters in mlx-vlm or train a model without adding _no_grad to the model class it results in a error.

```
from mlx_vlm.utils import load

model_path = "mlx-community/nanoLLaVA-1.5-bf16"
model, processor = load(model_path, processor_config={"trust_remote_code": True})
model.freeze()
```

and 

```
loss_and_grad_fn = nn.value_and_grad(model, self.loss_fn)
loss, grads = loss_and_grad_fn(model, batch)
```
Result in this error: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[29], [line 1](vscode-notebook-cell:?execution_count=29&line=1)
----> [1](vscode-notebook-cell:?execution_count=29&line=1) model.freeze()

File /opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:500, in Module.freeze(self, recurse, keys, strict)
    [497](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:497)     m._no_grad.update(local_keys)
    [499](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:499) if recurse:
--> [500](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:500)     self.apply_to_modules(_freeze_impl)
    [501](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:501) else:
    [502](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:502)     _freeze_impl("", self)

File /opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:414, in Module.apply_to_modules(self, apply_fn)
    [412](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:412) while module_stack:
    [413](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:413)     prefix, mod = module_stack.pop()
--> [414](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:414)     apply_fn(prefix, mod)
    [415](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:415)     prefix = "." + prefix if prefix else ""
    [416](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:416)     module_stack.extend(
    [417](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:417)         tree_flatten(mod.children(), prefix=prefix, is_leaf=self.is_module)
    [418](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:418)     )

File /opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:497, in Module.freeze.<locals>._freeze_impl(_, m)
    [494](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:494)     local_keys = [k for (k, v) in local_keys]
    [496](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:496) local_keys = m._validate_keys(local_keys, strict)
--> [497](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:497) m._no_grad.update(local_keys)

File /opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:103, in Module.__getattr__(self, key)
    [101](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:101)     return value
    [102](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:102) else:
--> [103](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniconda/base/envs/mlx_code/lib/python3.10/site-packages/mlx/nn/layers/base.py:103)     super(Module, self).__getattribute__(key)

AttributeError: 'Model' object has no attribute '_no_grad'
```

**To Reproduce**

Include code snippet
```python

```

**Expected behavior**

Freeze and train model paramteres.

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.1.2]: MacOS 14.5 Sonoma
 - Version [e.g. 0.7.0]: 0.17.2

**Additional context**

**Comment by awni** [comment] 2024-09-04 16:02
The problem is you didn't initialize the [super class in your Model](https://github.com/Blaizzy/mlx-vlm/blob/main/mlx_vlm/models/llava_bunny/llava_bunny.py#L120-L121). You need to add this line:

```
        super().__init__()
```

Closing for now. Let us know if you are still having issues after fixing that.

**Closed by awni** 2024-09-04 16:02 UTC
