### ISSUE TITLE
[BUG] mx.random.normal generates -inf

### ISSUE THREAD

**Issue by tyeah** [ml-explore/mlx#779] opened 2024-03-04 04:34 UTC
**Describe the bug**
mx.random.normal behaves differently when setting seed or setting key. And it generates inf sometimes.

**To Reproduce**

Include code snippet
```python

import mlx.core as mx

shape = (1, 64, 64, 4)
mx.random.seed(0)
x = mx.random.normal(shape=shape, dtype=mx.float16)
print(x.min(), x.max())

key = mx.random.key(0)
x = mx.random.normal(shape=shape, dtype=mx.float16, key=key)
print(x.min(), x.max())
```

outputs on my machine is
```python
array(-inf, dtype=float16) array(3.29688, dtype=float16)
array(-3.48633, dtype=float16) array(3.29688, dtype=float16)
```
**Expected behavior**
The 2 prints should print same value. And inf should never be part of mx.random.normal, given its extremely low probability.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.1
 - Version: current main (e6418781)

**Comment by awni** [comment] 2024-03-04 05:07
The fact that seed and key are different is expected. Seeding is not equivalent to passing an explicit key. The equivalent is (but this is an implementation detail that shouldn't be relied on):

```python
key = mx.random.key(0)
subkey, key = mx.random.split(key)
x = mx.random.normal(shape=shape, dtype=mx.float16, key=key)
print(x.min(), x.max())
```

**Comment by awni** [comment] 2024-03-04 05:09
As for the `inf`, that is a known issue with generating random numbers in fp16. For now I would suggest you use fp32 in the call to `random.normal` and then cast to the lower precision until we fix it.

I'm closing this as a duplicate of #642

**Closed by awni** 2024-03-04 05:09 UTC

**Comment by tyeah** [comment] 2024-03-04 06:05
> The fact that seed and key are different is expected. Seeding is not equivalent to passing an explicit key. The equivalent is (but this is an implementation detail that shouldn't be relied on):
> 
> ```python
> key = mx.random.key(0)
> subkey, key = mx.random.split(key)
> x = mx.random.normal(shape=shape, dtype=mx.float16, key=key)
> print(x.min(), x.max())
> ```

👍 Is it suggested to always use key, so that things are stateless?

**Comment by tyeah** [comment] 2024-03-04 06:05
> As for the `inf`, that is a known issue with generating random numbers in fp16. For now I would suggest you use fp32 in the call to `random.normal` and then cast to the lower precision until we fix it.
> 
> I'm closing this as a duplicate of #642

Thanks!

**Comment by awni** [comment] 2024-03-04 06:11
> Is it suggested to always use key, so that things are stateless?

Not necessarily, no. There are cases where you have to go that route, for example when vmapping with random number generation inside a function. But in most cases actually the stateless requirement is not that strict and using the global RNG state is actually fine.
