### ISSUE TITLE
[BUG] After upgrading to mlx 0.0.8, importing fails with: Library not loaded: @rpath/libgguflib.dylib

### ISSUE THREAD

**Issue by dastrobu** [ml-explore/mlx#434] opened 2024-01-11 21:29 UTC
After upgrading to mlx 0.0.8, importing fails with 

```
ImportError: dlopen(/Users/ds/code/ml/local/scale/venv/lib/python3.11/site-packages/mlx/core.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libgguflib.dylib
  Referenced from: <9411C83D-1676-3456-96D6-CC046A314DF3> /Users/ds/code/ml/local/scale/venv/lib/python3.11/site-packages/mlx/core.cpython-311-darwin.so
  Reason: tried: '/Users/ds/code/ml/local/scale/venv/lib/python3.11/site-packages/mlx/lib/libgguflib.dylib' (no such file), '/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/libgguflib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/libgguflib.dylib' (no such file), '/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/mlx/io/libgguflib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/mlx/io/libgguflib.dylib' (no such file), '/Users/ds/code/ml/local/scale/venv/lib/python3.11/site-packages/mlx/lib/libgguflib.dylib' (no such file), '/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/libgguflib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/libgguflib.dylib' (no such file), '/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/mlx/io/libgguflib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/a_katharopoulos/Library/com.circleci.runner/workdir/build/temp.macosx-11.1-arm64-cpython-311/mlx.core/mlx/io/libgguflib.dylib' (no such file), '/opt/homebrew/lib/libgguflib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libgguflib.dylib' (no such file), '/opt/homebrew/lib/libgguflib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libgguflib.dylib' (no such file)
```

The mention of `/Users/a_katharopoulos` on my local computer seems to be a sign that some paths are not configured correctly. 
I am not familiar with `libgguflib`, but it might be related to "Initial (and experimental) GGUF support"? 

I expect that some dependency must be installed using homebrew first. Can we mention this in the README/docs? I did not find it yet. 

**To Reproduce**

Include code snippet
```python
import mlx.core as mx
```

**Comment by awni** [comment] 2024-01-11 21:40
This is a problem with packaging GGUF. I mistakenly thought it was working but it looks like the library is not correctly packaged with the distribution. Will work on a fix ASAP, in the meantime please revert to 0.0.7 (or you can build from source which should be fine as well)

**Comment by dastrobu** [comment] 2024-01-11 21:46
Certainly, I just wanted to inform you about the issue without causing any inconvenience.

**Comment by awni** [comment] 2024-01-11 21:57
Fix in #435 will populate to PyPi in about 15 minutes. I will test and then close this issue once after that :)

**Comment by antirez** [comment] 2024-01-11 21:58
Thanks @awni !

**Comment by antirez** [comment] 2024-01-11 22:12
Works now.

**Comment by awni** [comment] 2024-01-11 22:14
Confirmed! Sorry for the SNAFU!

**Closed by awni** 2024-01-11 22:14 UTC
