### ISSUE TITLE
Why is `mx.eval` necessary after each iteration in the examples?

### ISSUE THREAD

**Issue by moskomule** [ml-explore/mlx#114] opened 2023-12-10 02:40 UTC
Hi, I'm excited to see a new ML framework (since JAX?)!

Among many features, I found the lazy evaluation interesting.
In the examples, such as `linear_regression.py`, weights are materialized by `mx.eval` after each iteration; see, for example,

https://github.com/ml-explore/mlx/blob/0b283996386bfe1bbe6c644bab8d3e3251f71ef0/examples/python/linear_regression.py#L36

Commenting this line out keeps the results the same, to my knowledge, as expected.
But it's used in other examples as well, so I suspect it's intentional.
Are there any reasons that `mx.eval` is necessary?

Thank you!

**Comment by awni** [comment] 2023-12-10 03:40
First I'd point you to the [quicksart guide](https://ml-explore.github.io/mlx/build/html/quick_start.html#), it has some information on this. Albeit we should add more docs on `eval` etc.

So if you do a computation in MLX it's lazy:
```
c = a + b 
```
At this point `c` just has a shape and a type but no data. The `+` operations hasn't actually been run yet. To get the output you have to `eval` the graph. One way to force that to happen is to call `mx.eval(c)`. It also happens implicitly in a few other cases such as printing `c`, calling `np.array(c)`, etc.

No work starts until you call `eval`.  For example:
```
for _ in range(100000):
  a = mx.exp(a)
```
Produces a pretty long graph. And nothing gets computed until an `eval` has been called (implicitly or explicitly). For the linear regression example it's fine because the graph is still manageable. But for really long running computations if the graph gets too big it can drain resources and slow things down, so a good approach is to do an eval every so often (like after one step of SGD).

**Comment by awni** [comment] 2023-12-10 03:40
I'll close this issue for now. Feel free to comment if you have any more questions.

**Closed by awni** 2023-12-10 03:40 UTC

**Comment by moskomule** [comment] 2023-12-10 04:02
Thank you for the concise answer!

So far, I have just tried linear regression and MNIST examples, so I didn't notice that evaluation of long-running graphs causes performance degeneration; rather, I found `mx.eval` introduces some overhead. I will try more complex problems.

If I understand it correctly, mlx dynamically creates graphs like PyTorch. I know some complicated problems need dynamic graphs, but for simple problems, including the linear regression example, graphs can be static. Are there any ways to reuse once-constructed graphs to reduce overhead?

**Comment by awni** [comment] 2023-12-14 21:41
> Are there any ways to reuse once-constructed graphs to reduce overhead?

Good question. At the moment no. In the future likely yes as we want to support a compiled path. However, we find our graph building overhead is really minimal in most cases so hopefully it shouldn't be too pressing for you. If you are running into graph overhead as a bottleneck, please share more information, that would be helpful to see.
